{% set name = "xorg-libXinerama" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/lib/{{ name.split('-')[1] }}-{{ version }}.tar.xz
  sha256: d00fc1599c303dc5cbc122b8068bdc7405d6fcb19060f4597fc51bd3a8be51d7

build:
  number: 0
  # xorg-libxdmcp, libxcb, libx11 aren't available on Windows because their dependencies clash with m2/msys2 and mingw64/ucrt64 toolchains.
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('xorg-libxinerama', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - gnuconfig
    - make
    - autoconf
    - automake
    - libtool
  host:
    - xorg-util-macros ==1.20.2
    - xorg-libx11 {{ xorg_libx11 }}
    - xorg-libxext {{ xorg_libxext }}
    - xorg-xorgproto {{ xorg_xorgproto }}

test:
  commands:
    - test -f $PREFIX/lib/libXinerama.dylib  # [osx]
    - test -f $PREFIX/lib/libXinerama.so     # [linux]

about:
  home: https://gitlab.freedesktop.org/xorg/lib/libxinerama
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libxinerama
  doc_url: https://gitlab.freedesktop.org/xorg/lib/libxinerama
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Client library for the Xinerama extension to the X11 protocol.
  description: |
    Client library for the Xinerama extension to the X11 protocol.
extra:
  recipe-maintainers:
    - hmaarrfk
